### ISSUE TITLE
please add support for SystemVerilog files (.sv, .svh, .v), VHDL files

### ISSUE THREAD

**Issue by jonnyboynewton** [Parth2031/Colorful-Comments#12]
Hi - can you please add support for SystemVerilog files (and maybe VHDL files too)?  this is the main language we use

**Comment by code-instable** [comment]
Hi,
It seems like the author does not work on this extension anymore, that's why I created recently a fork of this extension

If you want to add language support to this extension please check out [the newly forked Colorful Comments extension](https://github.com/allemand-instable/Colorful-Comments), where you can ask for language support in the issues ( make sure to read the README.md at adding language support section, so that it's easier for me to add it )

**Comment by allemand-instable** [comment]
suggested fix :

- languageConfig.yaml

```yaml
  # * SystemVerilog
  # https://github.com/Parth2031/Colorful-Comments/issues/12
  # according to extension : mshr-h.veriloghdl
  # github : https://github.com/mshr-h/vscode-verilog-hdl-support
  systemverilog: *c_delim
  vhdl: *double_dash_delim
```
